#pragma once
#include "sortlab/algorithms.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <cstdint>
#include <limits>
#include <numeric>
#include <vector>
namespace sortlab {

template<bool C> static void binary_insertion_range(std::vector<Value>& a,std::size_t lo,std::size_t hi,Stats& s){if(hi-lo<2)return;for(std::size_t i=lo+1;i<hi;++i){const Value v=a[i];std::size_t left=lo,right=i;while(left<right){const std::size_t mid=left+(right-left)/2;if(lessv<C>(v,a[mid],s))right=mid;else left=mid+1;}for(std::size_t j=i;j>left;--j)writev<C>(a[j],a[j-1],s);writev<C>(a[left],v,s);}}
template<bool C> static void binary_insertion_sort(std::vector<Value>& a,Stats& s){binary_insertion_range<C>(a,0,a.size(),s);}
template<bool C> static void comb_sort(std::vector<Value>& a,Stats& s){std::size_t gap=a.size();bool swapped=true;while(gap>1||swapped){gap=(gap*10)/13;if(gap<1)gap=1;swapped=false;for(std::size_t i=0;i+gap<a.size();++i)if(lessv<C>(a[i+gap],a[i],s)){swapv<C>(a[i],a[i+gap],s);swapped=true;}}}
static std::vector<std::size_t> pratt_gaps(std::size_t n){std::vector<std::size_t>gaps;for(std::size_t p2=1;p2<n;){for(std::size_t g=p2;g<n;){gaps.push_back(g);if(g>(n-1)/3)break;g*=3;}if(p2>(n-1)/2)break;p2*=2;}std::sort(gaps.begin(),gaps.end());gaps.erase(std::unique(gaps.begin(),gaps.end()),gaps.end());std::reverse(gaps.begin(),gaps.end());return gaps;}
template<bool C> static void shell_pratt_sort(std::vector<Value>&a,Stats&s){for(auto gap:pratt_gaps(a.size()))for(std::size_t i=gap;i<a.size();++i){Value v=a[i];std::size_t j=i;while(j>=gap&&lessv<C>(v,a[j-gap],s)){writev<C>(a[j],a[j-gap],s);j-=gap;}writev<C>(a[j],v,s);}}
template<bool C> static void merge_ranges(std::vector<Value>&a,std::vector<Value>&tmp,std::size_t lo,std::size_t mid,std::size_t hi,Stats&s){std::size_t i=lo,j=mid,k=lo;while(i<mid&&j<hi){if(lessv<C>(a[j],a[i],s))writev<C>(tmp[k++],a[j++],s);else writev<C>(tmp[k++],a[i++],s);}while(i<mid)writev<C>(tmp[k++],a[i++],s);while(j<hi)writev<C>(tmp[k++],a[j++],s);for(k=lo;k<hi;++k)writev<C>(a[k],tmp[k],s);}
template<bool C> static void merge_bottom_up_sort(std::vector<Value>&a,Stats&s){if(a.size()<2)return;std::vector<Value>tmp(a.size());for(std::size_t width=1;width<a.size();){for(std::size_t lo=0;lo<a.size();lo+=2*width){auto mid=std::min(a.size(),lo+width);auto hi=std::min(a.size(),lo+2*width);if(mid<hi)merge_ranges<C>(a,tmp,lo,mid,hi,s);}if(width>a.size()/2)break;width*=2;}}
template<bool C> static void natural_merge_sort(std::vector<Value>&a,Stats&s){if(a.size()<2)return;std::vector<Value>tmp(a.size());std::vector<std::pair<std::size_t,std::size_t>>runs;std::size_t lo=0;while(lo<a.size()){std::size_t hi=lo+1;if(hi<a.size()){if(lessv<C>(a[hi],a[lo],s)){while(hi<a.size()&&lessv<C>(a[hi],a[hi-1],s))++hi;std::reverse(a.begin()+static_cast<std::ptrdiff_t>(lo),a.begin()+static_cast<std::ptrdiff_t>(hi));if constexpr(C)s.writes+=static_cast<std::uint64_t>(hi-lo);}else while(hi<a.size()&&!lessv<C>(a[hi],a[hi-1],s))++hi;}runs.emplace_back(lo,hi);lo=hi;}while(runs.size()>1){std::vector<std::pair<std::size_t,std::size_t>>next;next.reserve((runs.size()+1)/2);for(std::size_t r=0;r<runs.size();r+=2){if(r+1==runs.size()){next.push_back(runs[r]);continue;}auto[a0,a1]=runs[r];auto[b0,b1]=runs[r+1];(void)b0;merge_ranges<C>(a,tmp,a0,a1,b1,s);next.emplace_back(a0,b1);}runs.swap(next);}}
template<bool C> static void merge_insertion_rec(std::vector<Value>&a,std::vector<Value>&tmp,std::size_t lo,std::size_t hi,std::size_t cutoff,Stats&s){if(hi-lo<=cutoff){insertion_range<C>(a,lo,hi,s);return;}const auto mid=lo+(hi-lo)/2;merge_insertion_rec<C>(a,tmp,lo,mid,cutoff,s);merge_insertion_rec<C>(a,tmp,mid,hi,cutoff,s);if(!lessv<C>(a[mid],a[mid-1],s))return;merge_ranges<C>(a,tmp,lo,mid,hi,s);}
template<bool C> static void merge_insertion_runtime(std::vector<Value>&a,Stats&s,std::size_t cutoff){if(a.size()<2)return;if(cutoff<1)cutoff=1;std::vector<Value>tmp(a.size());merge_insertion_rec<C>(a,tmp,0,a.size(),cutoff,s);}
template<bool C> static void merge_insertion_24(std::vector<Value>&a,Stats&s){merge_insertion_runtime<C>(a,s,24);}
static Value median3_value(Value x,Value y,Value z,Stats&s,bool count){auto lt=[&](Value a,Value b){if(count)++s.comparisons;return a<b;};if(lt(x,y)){if(lt(y,z))return y;return lt(x,z)?z:x;}if(lt(x,z))return x;return lt(y,z)?z:y;}
template<bool C> static std::size_t median3_partition(std::vector<Value>&a,std::size_t lo,std::size_t hi,Stats&s){const std::size_t mid=lo+(hi-lo)/2;const Value pivot=median3_value(a[lo],a[mid],a[hi-1],s,C);std::size_t i=lo,j=hi-1;for(;;){while(i<hi&&lessv<C>(a[i],pivot,s))++i;while(j>lo&&lessv<C>(pivot,a[j],s))--j;if(i>=j)return i;swapv<C>(a[i],a[j],s);++i;if(j>0)--j;}}
template<bool C> static void quick_median3_rec(std::vector<Value>&a,std::size_t lo,std::size_t hi,Stats&s,std::size_t cutoff){while(hi-lo>cutoff){auto cut=median3_partition<C>(a,lo,hi,s);if(cut<=lo)cut=lo+1;if(cut>=hi)cut=hi-1;if(cut-lo<hi-cut){quick_median3_rec<C>(a,lo,cut,s,cutoff);lo=cut;}else{quick_median3_rec<C>(a,cut,hi,s,cutoff);hi=cut;}}if(cutoff>1)insertion_range<C>(a,lo,hi,s);}
template<bool C> static void quick_median3_sort(std::vector<Value>&a,Stats&s){if(!a.empty())quick_median3_rec<C>(a,0,a.size(),s,1);}
template<bool C> static void quick_insertion_runtime(std::vector<Value>&a,Stats&s,std::size_t cutoff){if(a.empty())return;if(cutoff<1)cutoff=1;quick_median3_rec<C>(a,0,a.size(),s,cutoff);}
template<bool C> static void quick_insertion_24(std::vector<Value>&a,Stats&s){quick_insertion_runtime<C>(a,s,24);}
template<bool C> static void intro_cutoff_rec(std::vector<Value>&a,std::size_t lo,std::size_t hi,unsigned depth,std::size_t cutoff,Stats&s){while(hi-lo>cutoff){if(depth==0){heap_sort_range<C>(a,lo,hi,s);return;}--depth;std::size_t cut=hoare_partition<C>(a,lo,hi,s);if(cut<=lo)cut=lo+1;if(cut>=hi)cut=hi-1;if(cut-lo<hi-cut){intro_cutoff_rec<C>(a,lo,cut,depth,cutoff,s);lo=cut;}else{intro_cutoff_rec<C>(a,cut,hi,depth,cutoff,s);hi=cut;}}if(cutoff>1)insertion_range<C>(a,lo,hi,s);}
template<bool C> static void intro_cutoff_runtime(std::vector<Value>&a,Stats&s,std::size_t cutoff){if(a.size()<2)return;if(cutoff<1)cutoff=1;const auto bits=std::bit_width(a.size());const unsigned depth=static_cast<unsigned>(2*(bits-1));intro_cutoff_rec<C>(a,0,a.size(),depth,cutoff,s);}
template<bool C> static void dual_pivot_rec(std::vector<Value>&a,std::ptrdiff_t lo,std::ptrdiff_t hi,Stats&s){if(lo>=hi)return;auto at=[&](std::ptrdiff_t i)->Value&{return a[static_cast<std::size_t>(i)];};if(lessv<C>(at(hi),at(lo),s))swapv<C>(at(lo),at(hi),s);const Value p=at(lo),q=at(hi);std::ptrdiff_t lt=lo+1,gt=hi-1,i=lt;while(i<=gt){if(lessv<C>(at(i),p,s)){swapv<C>(at(i),at(lt),s);++lt;++i;}else if(lessv<C>(q,at(i),s)){while(i<gt&&lessv<C>(q,at(gt),s))--gt;swapv<C>(at(i),at(gt),s);--gt;if(lessv<C>(at(i),p,s)){swapv<C>(at(i),at(lt),s);++lt;}++i;}else ++i;}--lt;++gt;swapv<C>(at(lo),at(lt),s);swapv<C>(at(hi),at(gt),s);dual_pivot_rec<C>(a,lo,lt-1,s);if(lessv<C>(p,q,s))dual_pivot_rec<C>(a,lt+1,gt-1,s);dual_pivot_rec<C>(a,gt+1,hi,s);}
template<bool C> static void dual_pivot_sort(std::vector<Value>&a,Stats&s){if(a.size()>1)dual_pivot_rec<C>(a,0,static_cast<std::ptrdiff_t>(a.size()-1),s);}
template<bool C> static void radix_lsd_11_sort(std::vector<Value>&a,Stats&s){if(a.size()<2)return;std::vector<Value>tmp(a.size());constexpr std::uint64_t sign=std::uint64_t{1}<<63;constexpr unsigned bits=11;constexpr std::size_t buckets=1U<<bits;std::array<std::size_t,buckets>count{};std::array<std::size_t,buckets>pos{};for(unsigned shift=0;shift<64;shift+=bits){const unsigned width=std::min(bits,64U-shift);const std::uint64_t mask=(std::uint64_t{1}<<width)-1;count.fill(0);for(Value v:a){auto key=static_cast<std::uint64_t>(v)^sign;++count[static_cast<std::size_t>((key>>shift)&mask)];}pos[0]=0;const std::size_t used=std::size_t{1}<<width;for(std::size_t i=1;i<used;++i)pos[i]=pos[i-1]+count[i-1];for(Value v:a){auto key=static_cast<std::uint64_t>(v)^sign;auto b=static_cast<std::size_t>((key>>shift)&mask);writev<C>(tmp[pos[b]++],v,s);}a.swap(tmp);}}
template<bool C> static void std_heap_sort(std::vector<Value>&a,Stats&s){auto cmp=[&](Value x,Value y){if constexpr(C)++s.comparisons;return x<y;};std::make_heap(a.begin(),a.end(),cmp);std::sort_heap(a.begin(),a.end(),cmp);}
#define XALG(N,F,FN,Q,CMP,ST,IP,AD,B,A,W,AUX) Algorithm{N,F,FN<false>,FN<true>,Q,CMP,ST,IP,AD,B,A,W,AUX}
inline const std::vector<Algorithm>& all_algorithms(){static const std::vector<Algorithm>table=[](){std::vector<Algorithm>out=algorithms();const std::vector<Algorithm>extra={XALG("binary_insertion","insertion",binary_insertion_sort,true,true,"yes","yes","yes","O(n log n) comparisons / O(n^2) moves","O(n^2)","O(n^2)","O(1)"),XALG("comb","exchange",comb_sort,true,true,"no","yes","partial","gap-dependent","gap-dependent","O(n^2)","O(1)"),XALG("shell_pratt","shell",shell_pratt_sort,false,true,"no","yes","yes","gap-dependent","gap-dependent","O(n log^2 n) comparisons","O(log n) gaps"),XALG("merge_bottom_up","merge",merge_bottom_up_sort,false,true,"yes","no","no","O(n log n)","O(n log n)","O(n log n)","O(n)"),XALG("natural_merge","merge-adaptive",natural_merge_sort,false,true,"yes","no","runs","O(n)","O(n log n)","O(n log n)","O(n)"),XALG("merge_insertion_24","hybrid",merge_insertion_24,false,true,"yes","no","small-runs","O(n)","O(n log n)","O(n log n)","O(n)"),XALG("quick_median3","quick",quick_median3_sort,false,true,"no","yes","pivot-sampling","O(n log n)","O(n log n)","O(n^2)","O(log n) expected stack"),XALG("quick_insertion_24","hybrid",quick_insertion_24,false,true,"no","yes","small-partitions","O(n log n)","O(n log n)","O(n^2)","O(log n) expected stack"),XALG("dual_pivot","quick",dual_pivot_sort,false,true,"no","yes","duplicates/pivots","O(n log n)","O(n log n)","O(n^2)","O(log n) expected stack"),XALG("radix_lsd_11","distribution",radix_lsd_11_sort,false,false,"yes","no","digit-width","O(6n)","O(6n)","O(6n)","O(n + 2048)"),XALG("std_heap","library",std_heap_sort,false,true,"no","yes","implementation","O(n log n)","O(n log n)","O(n log n)","implementation")};out.insert(out.end(),extra.begin(),extra.end());return out;}();return table;}
#undef XALG
}
