#include "sortlab/allocation_tracker.hpp"
#include "sortlab/extended_algorithms.hpp"
#include "sortlab/workloads.hpp"
#include <algorithm>
#include <cstdint>
#include <iostream>
#include <numeric>
#include <stdexcept>
#include <string>
#include <string_view>
#include <vector>
using namespace sortlab;
static std::vector<std::string> split(std::string_view x){std::vector<std::string>o;std::size_t p=0;while(p<=x.size()){auto e=x.find(',',p);auto t=x.substr(p,e==std::string_view::npos?x.size()-p:e-p);if(t.empty())throw std::runtime_error("empty item");o.emplace_back(t);if(e==std::string_view::npos)break;p=e+1;}return o;}
static std::vector<std::size_t> nums(std::string_view x){std::vector<std::size_t>o;for(const auto&s:split(x))o.push_back(static_cast<std::size_t>(std::stoull(s)));return o;}
static std::vector<std::size_t> select(const std::vector<std::string>& names){const auto&t=all_algorithms();std::vector<std::size_t>o;if(names.empty()){o.resize(t.size());std::iota(o.begin(),o.end(),0);return o;}for(const auto&name:names){auto it=std::find_if(t.begin(),t.end(),[&](const Algorithm&a){return a.name==name;});if(it==t.end())throw std::runtime_error("unknown algorithm: "+name);o.push_back(static_cast<std::size_t>(std::distance(t.begin(),it)));}return o;}
static allocation_tracker::Snapshot measure(const Algorithm&alg,const std::vector<Value>&input){auto a=input;Stats s;allocation_tracker::start();alg.timed(a,s);auto snap=allocation_tracker::stop();if(!verify(input,a))throw std::runtime_error("verification failed for "+std::string(alg.name));return snap;}
static int self_test(){auto input=make_data("random",4096,trial_seed(1,"random",4096,0));const auto&t=all_algorithms();auto find=[&](std::string_view n)->const Algorithm&{return *std::find_if(t.begin(),t.end(),[&](const Algorithm&a){return a.name==n;});};auto heap=measure(find("heap"),input);auto merge=measure(find("merge"),input);auto radix=measure(find("radix_lsd"),input);if(heap.calls!=0||merge.calls==0||radix.calls==0){std::cerr<<"FAIL allocation classification\n";return 1;}std::cout<<"PASS: allocation tracker distinguishes in-place and allocating algorithms\n";return 0;}
int main(int argc,char**argv){try{bool test=false;int trials=5;std::uint64_t seed=0xA110CULL;std::vector<std::size_t>sizes={1024,16384,262144};std::vector<std::string>patterns={"random","few_unique","nearly_sorted"};std::vector<std::string>names;for(int i=1;i<argc;++i){std::string a=argv[i];if(a=="--self-test")test=true;else if(a=="--trials"&&i+1<argc)trials=std::stoi(argv[++i]);else if(a=="--seed"&&i+1<argc)seed=std::stoull(argv[++i]);else if(a=="--sizes"&&i+1<argc)sizes=nums(argv[++i]);else if(a=="--patterns"&&i+1<argc)patterns=split(argv[++i]);else if(a=="--algorithms"&&i+1<argc)names=split(argv[++i]);else if(a=="--help"){std::cout<<"sort_alloc [--trials N] [--sizes csv] [--patterns csv] [--algorithms csv]\n";return 0;}else throw std::runtime_error("bad argument: "+a);}if(test)return self_test();if(trials<1)throw std::runtime_error("trials must be positive");const auto selected=select(names);const auto&t=all_algorithms();std::cout<<"schema_version,algorithm,pattern,n,trial,trial_seed,input_hash,allocation_calls,total_requested_bytes,peak_live_bytes,max_single_allocation_bytes,live_bytes_at_stop,verified\n";for(auto n:sizes)for(const auto&p:patterns)for(int trial=0;trial<trials;++trial){auto ts=trial_seed(seed,p,n,static_cast<std::uint64_t>(trial));auto input=make_data(p,n,ts);auto fp=input_hash(input);for(auto idx:selected){auto snap=measure(t[idx],input);std::cout<<1<<','<<t[idx].name<<','<<p<<','<<n<<','<<trial<<','<<ts<<','<<fp<<','<<snap.calls<<','<<snap.total_requested<<','<<snap.peak_live<<','<<snap.max_single<<','<<snap.live_at_stop<<",1\n";}}return 0;}catch(const std::exception&e){std::cerr<<"error: "<<e.what()<<'\n';return 2;}}
