include_guard(GLOBAL)

# Retained pre-migration empirical executables.  They intentionally remain
# outside the installed/public sortlab target and exist only to reproduce or
# compare historical evidence until EddyTodd/bench migration acceptance passes.
function(sortlab_research_executable target source)
  add_executable(${target} ${source})
  target_link_libraries(${target} PRIVATE sortlab::sortlab)
  target_include_directories(${target} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/research/include)
  set_target_properties(${target} PROPERTIES CXX_EXTENSIONS OFF)
  sortlab_apply_warnings(${target})
  if(NOT target STREQUAL "sort_alloc")
    sortlab_apply_sanitizers(${target})
  endif()
endfunction()

sortlab_research_executable(sort_lab research/apps/sort_lab.cpp)
sortlab_research_executable(sort_records research/apps/sort_records.cpp)
sortlab_research_executable(sort_cutoffs research/apps/sort_cutoffs.cpp)
sortlab_research_executable(sort_perf research/apps/sort_perf.cpp)
sortlab_research_executable(sort_alloc research/apps/sort_alloc.cpp)
sortlab_research_executable(sort_tiny research/apps/sort_tiny.cpp)
sortlab_research_executable(sort_leaf_hybrids research/apps/sort_leaf_hybrids.cpp)
sortlab_research_executable(sort_merge_policies research/apps/sort_merge_policies.cpp)
sortlab_research_executable(sort_merge_kernels research/apps/sort_merge_kernels.cpp)
sortlab_research_executable(sort_adaptive_records research/apps/sort_adaptive_records.cpp)
sortlab_research_executable(adaptive_record_kernel_contract research/apps/adaptive_record_kernel_contract.cpp)
include(${CMAKE_CURRENT_LIST_DIR}/ExternalBaselines.cmake)

function(sortlab_register_retained_research_tests)
  if(NOT BUILD_TESTING OR NOT SORTLAB_BUILD_TESTS)
    return()
  endif()

  add_test(NAME sort_self_test COMMAND sort_lab --self-test)
  add_test(NAME sort_smoke_benchmark COMMAND sort_lab --trials 2 --warmups 0 --sizes 0,1,32,257 --patterns random,binary,all_equal,organ_pipe,rotated,plateau --algorithms insertion,binary_insertion,heap,natural_merge,merge_insertion_24,quick_3way,dual_pivot,intro,radix_lsd_11,std_sort)
  add_test(NAME record_self_test COMMAND sort_records --self-test)
  add_test(NAME record_smoke_benchmark COMMAND sort_records --trials 2 --warmups 0 --sizes 0,1,32,257 --payload-words 0,7 --patterns few_unique,all_equal,rotated,plateau --algorithms insertion,heap,merge,quick_3way,intro,radix_lsd,std_sort,std_stable_sort)
  add_test(NAME cutoff_self_test COMMAND sort_cutoffs --self-test)
  add_test(NAME perf_self_test COMMAND sort_perf --self-test)
  add_test(NAME allocation_self_test COMMAND sort_alloc --self-test)
  add_test(NAME tiny_kernel_self_test COMMAND sort_tiny --self-test)
  add_test(NAME leaf_hybrid_self_test COMMAND sort_leaf_hybrids --self-test)
  add_test(NAME adaptive_merge_self_test COMMAND sort_merge_policies --self-test)
  add_test(NAME adaptive_merge_kernel_self_test COMMAND sort_merge_kernels --self-test)
  add_test(NAME adaptive_record_self_test COMMAND sort_adaptive_records --self-test)
  add_test(NAME adaptive_record_backward_gallop_contract COMMAND adaptive_record_kernel_contract)
  add_test(NAME tiny_kernel_smoke_benchmark COMMAND sort_tiny --trials 2 --warmups 0 --sizes 2,7,16,31 --patterns random,sorted,few_unique --kernels insertion,binary_insertion,bitonic_network,std_sort)
  add_test(NAME leaf_hybrid_smoke_benchmark COMMAND sort_leaf_hybrids --trials 3 --warmups 0 --sizes 64,257 --patterns random,sorted,few_unique --cutoffs 4,16,32)
  add_test(NAME adaptive_merge_smoke_benchmark COMMAND sort_merge_policies --trials 2 --warmups 0 --sizes 31,64,315 --patterns random,sorted,run_long_short,run_fibonacci --policies pairwise,timsort_stack,powersort --minruns none,classic,balanced)
  add_test(NAME adaptive_merge_kernel_smoke_benchmark COMMAND sort_merge_kernels --trials 2 --warmups 0 --sizes 64,315 --patterns random,run_long_short,run_alternating_direction --gallop-thresholds 4,7)
  add_test(NAME adaptive_record_smoke_benchmark COMMAND sort_adaptive_records --trials 2 --warmups 0 --sizes 31,64,315 --payload-words 0,7,31 --patterns few_unique,binary,run_long_short,run_alternating_direction --policies timsort_stack,powersort --minruns classic,balanced --buffers full,smaller --searches linear,gallop --gallop-thresholds 4,7)

  find_package(Python3 COMPONENTS Interpreter QUIET)
  if(Python3_Interpreter_FOUND)
    add_test(NAME analysis_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/analyze.py --self-test)
    add_test(NAME record_analysis_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/analyze_records.py --self-test)
    add_test(NAME crossover_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/crossovers.py --self-test)
    add_test(NAME cutoff_tuning_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/tune_cutoffs.py --self-test)
    add_test(NAME claim_matrix_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/claim_matrix.py --self-test)
    add_test(NAME perf_analysis_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/analyze_perf.py --self-test)
    add_test(NAME allocation_analysis_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/analyze_alloc.py --self-test)
    add_test(NAME portfolio_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/portfolio.py --self-test)
    add_test(NAME campaign_pipeline_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/campaign.py --self-test)
    add_test(NAME artifact_validation_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/validate_artifacts.py --self-test)
    add_test(NAME evidence_ledger_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/evidence_ledger.py --self-test)
    add_test(NAME research_report_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/report.py --self-test)
    add_test(NAME external_bootstrap_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/bootstrap_external.py --self-test)
    add_test(NAME tiny_analysis_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/analyze_tiny.py --self-test)
    add_test(NAME leaf_kernel_tuning_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/tune_leaf_kernels.py --self-test)
    add_test(NAME adaptive_merge_analysis_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/analyze_merge_policies.py --self-test)
    add_test(NAME merge_policy_model_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/merge_policy_model.py --self-test)
    add_test(NAME adaptive_merge_kernel_analysis_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/analyze_merge_kernels.py --self-test)
    add_test(NAME gallop_tuning_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/tune_gallop.py --self-test)
    add_test(NAME adaptive_record_analysis_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/analyze_adaptive_records.py --self-test)
    add_test(NAME adaptive_record_width_analysis_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/analyze_record_width_effects.py --self-test)
    add_test(NAME adaptive_record_gallop_tuning_self_test COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tools/tune_record_gallop.py --self-test)
  endif()
endfunction()
