cmake_minimum_required(VERSION 3.23)

get_filename_component(RELEASE_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

function(_release_read path out_var)
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Required release metadata file is missing: ${path}")
  endif()
  file(READ "${path}" content)
  set(${out_var} "${content}" PARENT_SCOPE)
endfunction()

function(_release_require_contains path needle label)
  _release_read("${path}" content)
  string(FIND "${content}" "${needle}" found)
  if(found EQUAL -1)
    message(FATAL_ERROR "${label} does not contain expected release value: ${needle}")
  endif()
endfunction()

_release_read("${RELEASE_ROOT}/CMakeLists.txt" cmake_text)
string(REGEX MATCH
  "project\\([^\\)]*VERSION[ \t\r\n]+([0-9]+\\.[0-9]+\\.[0-9]+)"
  project_declaration
  "${cmake_text}")
if(NOT project_declaration)
  message(FATAL_ERROR "Could not derive semantic version from top-level project(...) declaration")
endif()
set(release_version "${CMAKE_MATCH_1}")
string(REPLACE "." ";" release_parts "${release_version}")
list(GET release_parts 0 release_major)
list(GET release_parts 1 release_minor)
list(GET release_parts 2 release_patch)

file(GLOB version_headers "${RELEASE_ROOT}/include/*/version.hpp")
list(LENGTH version_headers version_header_count)
if(NOT version_header_count EQUAL 1)
  message(FATAL_ERROR "Expected exactly one public include/*/version.hpp; found ${version_header_count}")
endif()
list(GET version_headers 0 version_header)
_release_read("${version_header}" version_header_text)
_release_require_contains("${version_header}" "\"${release_version}\"" "public version header")

foreach(component major minor patch)
  if(component STREQUAL "major")
    set(expected_component "${release_major}")
  elseif(component STREQUAL "minor")
    set(expected_component "${release_minor}")
  else()
    set(expected_component "${release_patch}")
  endif()
  string(REGEX MATCH "version_${component}[ \t]*=[ \t]*([0-9]+)" lower_component_declaration "${version_header_text}")
  if(lower_component_declaration)
    set(actual_component "${CMAKE_MATCH_1}")
  else()
    string(TOUPPER "${component}" upper_component)
    string(REGEX MATCH "[A-Za-z0-9_]*VERSION_${upper_component}[ \t]+([0-9]+)" macro_component_declaration "${version_header_text}")
    if(NOT macro_component_declaration)
      message(FATAL_ERROR "Public version header does not expose numeric ${component} metadata")
    endif()
    set(actual_component "${CMAKE_MATCH_1}")
  endif()
  if(NOT actual_component STREQUAL expected_component)
    message(FATAL_ERROR "Public version header ${component} mismatch: CMake=${expected_component}, header=${actual_component}")
  endif()
endforeach()

set(citation_path "${RELEASE_ROOT}/CITATION.cff")
if(NOT EXISTS "${citation_path}")
  message(FATAL_ERROR "Required release metadata file is missing: ${citation_path}")
endif()
file(STRINGS "${citation_path}" citation_version_lines REGEX "^version:[ \t]+")
list(LENGTH citation_version_lines citation_version_count)
if(NOT citation_version_count EQUAL 1)
  message(FATAL_ERROR "CITATION.cff must contain exactly one version field")
endif()
list(GET citation_version_lines 0 citation_version_line)
if(NOT citation_version_line STREQUAL "version: ${release_version}")
  message(FATAL_ERROR "CITATION.cff version mismatch: expected 'version: ${release_version}', got '${citation_version_line}'")
endif()
file(STRINGS "${citation_path}" citation_date_lines REGEX "^date-released:[ \t]+")
list(LENGTH citation_date_lines citation_date_count)
if(NOT citation_date_count EQUAL 1)
  message(FATAL_ERROR "CITATION.cff must contain exactly one date-released field")
endif()
list(GET citation_date_lines 0 citation_date_line)
string(REGEX MATCH "^date-released:[ \t]+([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])$" citation_date_match "${citation_date_line}")
if(NOT citation_date_match)
  message(FATAL_ERROR "CITATION.cff date-released must use YYYY-MM-DD")
endif()
set(citation_date "${CMAKE_MATCH_1}")

set(changelog_path "${RELEASE_ROOT}/CHANGELOG.md")
if(NOT EXISTS "${changelog_path}")
  message(FATAL_ERROR "Required release metadata file is missing: ${changelog_path}")
endif()
file(STRINGS "${changelog_path}" changelog_release_lines REGEX "^## \\[${release_version}\\]")
list(LENGTH changelog_release_lines changelog_release_count)
if(NOT changelog_release_count EQUAL 1)
  message(FATAL_ERROR "CHANGELOG.md must contain exactly one release heading for ${release_version}")
endif()
list(GET changelog_release_lines 0 changelog_release_line)
string(REGEX MATCH "^## \\[${release_version}\\][ \t]+-[ \t]+([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])$" changelog_release_match "${changelog_release_line}")
if(NOT changelog_release_match)
  message(FATAL_ERROR "CHANGELOG.md release heading must be '## [${release_version}] - YYYY-MM-DD'")
endif()
set(changelog_date "${CMAKE_MATCH_1}")
if(NOT changelog_date STREQUAL citation_date)
  message(FATAL_ERROR "Release date mismatch for ${release_version}: CITATION.cff=${citation_date}, CHANGELOG.md=${changelog_date}")
endif()

if(EXISTS "${RELEASE_ROOT}/pyproject.toml")
  _release_require_contains("${RELEASE_ROOT}/pyproject.toml" "version = \"${release_version}\"" "pyproject.toml")
endif()
if(EXISTS "${RELEASE_ROOT}/benchctl/__init__.py")
  _release_require_contains("${RELEASE_ROOT}/benchctl/__init__.py" "__version__ = \"${release_version}\"" "benchctl/__init__.py")
endif()

if(EXISTS "${RELEASE_ROOT}/SUBJECTS.lock")
  find_program(RELEASE_GIT git REQUIRED)
  file(STRINGS "${RELEASE_ROOT}/SUBJECTS.lock" subject_lines REGEX "^[A-Za-z0-9_-]+[ \t]+[0-9a-f]+")
  list(LENGTH subject_lines subject_lock_count)
  if(subject_lock_count EQUAL 0)
    message(FATAL_ERROR "SUBJECTS.lock exists but contains no subject revisions")
  endif()
  set(lock_names)
  foreach(line IN LISTS subject_lines)
    string(REGEX MATCH "^([^ \t]+)[ \t]+([0-9a-f]+)[ \t]+" parsed "${line}")
    if(NOT parsed)
      message(FATAL_ERROR "Malformed SUBJECTS.lock entry: ${line}")
    endif()
    set(subject_name "${CMAKE_MATCH_1}")
    set(subject_sha "${CMAKE_MATCH_2}")
    string(LENGTH "${subject_sha}" subject_sha_length)
    if(NOT subject_sha_length EQUAL 40)
      message(FATAL_ERROR "SUBJECTS.lock SHA for ${subject_name} is not 40 hex characters")
    endif()
    list(FIND lock_names "${subject_name}" duplicate_index)
    if(NOT duplicate_index EQUAL -1)
      message(FATAL_ERROR "Duplicate SUBJECTS.lock entry for ${subject_name}")
    endif()
    list(APPEND lock_names "${subject_name}")
    execute_process(COMMAND "${RELEASE_GIT}" -C "${RELEASE_ROOT}" rev-parse "HEAD:subjects/${subject_name}" RESULT_VARIABLE gitlink_result OUTPUT_VARIABLE gitlink_sha ERROR_VARIABLE gitlink_error OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT gitlink_result EQUAL 0)
      message(FATAL_ERROR "Could not resolve gitlink for ${subject_name}: ${gitlink_error}")
    endif()
    if(NOT gitlink_sha STREQUAL subject_sha)
      message(FATAL_ERROR "SUBJECTS.lock mismatch for ${subject_name}: lock=${subject_sha}, gitlink=${gitlink_sha}")
    endif()
  endforeach()
  execute_process(COMMAND "${RELEASE_GIT}" -C "${RELEASE_ROOT}" ls-tree "HEAD:subjects" RESULT_VARIABLE subject_tree_result OUTPUT_VARIABLE subject_tree_output ERROR_VARIABLE subject_tree_error OUTPUT_STRIP_TRAILING_WHITESPACE)
  if(NOT subject_tree_result EQUAL 0)
    message(FATAL_ERROR "Could not enumerate committed subject gitlinks: ${subject_tree_error}")
  endif()
  string(REPLACE "\n" ";" subject_tree_lines "${subject_tree_output}")
  set(gitlink_names)
  foreach(tree_line IN LISTS subject_tree_lines)
    if(tree_line STREQUAL "")
      continue()
    endif()
    string(REGEX MATCH "^160000[ \t]+commit[ \t]+[0-9a-f]+[ \t]+(.+)$" gitlink_match "${tree_line}")
    if(NOT gitlink_match)
      message(FATAL_ERROR "subjects/ contains a committed entry that is not a gitlink: ${tree_line}")
    endif()
    set(gitlink_name "${CMAKE_MATCH_1}")
    list(APPEND gitlink_names "${gitlink_name}")
    list(FIND lock_names "${gitlink_name}" lock_index)
    if(lock_index EQUAL -1)
      message(FATAL_ERROR "Committed subject gitlink ${gitlink_name} is missing from SUBJECTS.lock")
    endif()
  endforeach()
  list(LENGTH gitlink_names gitlink_count)
  if(NOT gitlink_count EQUAL subject_lock_count)
    message(FATAL_ERROR "SUBJECTS.lock/gitlink count mismatch: lock=${subject_lock_count}, gitlinks=${gitlink_count}")
  endif()
endif()

message(STATUS "Release metadata verified for version ${release_version}")
